### ISSUE TITLE
[Fabric 1.20.1] When alongside "Paragliders" mod, Spectate mode is switched on when achieving 10 deaths despite having more than 10 lives present.

### ISSUE THREAD

**Issue by DeltaGaiya** [MianReplicate/Lifesteal#19]
**_Versions_**
Minecraft Version: 1.20.1
Loader Version: PolyMC 6.1 (Worth noting that this happened on the default Minecraft launcher, Version 1.10.2
Mod Version: 7.0.0
(For the sake of it,) Paragliders Mod Version: 20.1.3
Fabric API Version: 0.92.2+1.20.1

**Describe the bug**
Spectate Mode is applied to the player (me, in this case–single player) when going over ten deaths, even though I have more than ten hearts to pull from as a result of using the "Paragliders" mod to apply hearts through the Spirit Orb > Heart Container method. Upon switching to Survival Mode out of Spectate, my lives are at the full amount + whatever hearts were added from the Heart Containers.

**To Reproduce**
1. Open a world (decided to make a new world for the sake of demonstration)
2. Go to a Statue with Spirit Orbs, and spend any mount of them towards getting a Heart Container.
3. Die. (More than ten times)

**Expected behavior**
I shouldn't be booted into Spectate Mode until after all of my lives have been depleted, but it instead happens after ten deaths have been counted.

Video Link: [https://youtu.be/pWgahAFB1jo](url) (hopefully I set that up right) (good enough)

**Comment by MianReplicate** [comment]
After some testing, I can verify this does happen. Thank you for the report. I will fix this whenever I have the time.

**Comment by MianReplicate** [comment]
After some debugging, I can say that the bug happens because when the player respawns, the health modifier from the "Paragliders" mod is not added by the time "Lifesteal" checks how many hearts the player has. Therefore, to "Lifesteal", it believes that the player has ran out of hearts because "Paragliders" has not added in hearts at that time.

This will be a bit difficult to fix because as far as my knowledge goes, there is no way to guarantee my mod if more modifiers will show up. I will let you know when a fix is found.

**Comment by DeltaGaiya** [comment]
> After some debugging, I can say that the bug happens because when the player respawns, the health modifier from the "Paragliders" mod is not added by the time "Lifesteal" checks how many hearts the player has. Therefore, to "Lifesteal", it believes that the player has ran out of hearts because "Paragliders" has not added in hearts at that time.
> 
> This will be a bit difficult to fix because as far as my knowledge goes, there is no way to guarantee my mod if more modifiers will show up. I will let you know when a fix is found.


I seeeee, didn’t think the issue would be like this but at least it can be identified
Honestly no worries if the issue can’t be resolved at the end of the day, I appreciate the work you’ve been doing regardless

**Comment by MianReplicate** [comment]
Just wanted to put a comment here to reassure that this issue is still going to be looked into sometime. I honestly just haven't been into MC modding lately and have only been focused on porting the mod to newer versions of MC when needed. Sorry if it causes any inconvenience. (even though I know you don't expect one :) )

**Comment by DeltaGaiya** [comment]
> Just wanted to put a comment here to reassure that this issue is still going to be looked into sometime. I honestly just haven't been into MC modding lately and have only been focused on porting the mod to newer versions of MC when needed. Sorry if it causes any inconvenience. (even though I know you don't expect one :) )

I hear you I hear you, I absolutely appreciate the update

I hear you on the focusing on other stuff part, I'm in no rush to have it working at the moment so you can definitely take your time 🙏
